api/src/Entity/RateRule.php
<?php

namespace App\Entity;

use App\Repository\RateRuleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RateRuleRepository::class)
 */
class RateRule
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_start;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_end;

    /**
     * @ORM\ManyToOne(targetEntity=RateType::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $rate_type;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $base_rate_variable;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $base_rate_fix;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $length_min;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $length_max;

    /**
     * @ORM\ManyToOne(targetEntity=Property::class, inversedBy="rateRules")
     * @ORM\JoinColumn(nullable=false)
     */
    private $property;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $priority;

    /**
     * @ORM\Column(type="boolean")
     */
    private $default_selection;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $day_selection = [];

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $pax_min;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $pax_max;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $occupancy_min;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $occupancy_max;

    /**
     * @ORM\ManyToOne(targetEntity=Age::class)
     */
    private $age_min;

    /**
     * @ORM\ManyToOne(targetEntity=Age::class)
     */
    private $age_max;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(\DateTimeInterface $date_start): self
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(\DateTimeInterface $date_end): self
    {
        $this->date_end = $date_end;

        return $this;
    }

    public function getRateType(): ?RateType
    {
        return $this->rate_type;
    }

    public function setRateType(?RateType $rate_type): self
    {
        $this->rate_type = $rate_type;

        return $this;
    }

    public function getBaseRateVariable(): ?float
    {
        return $this->base_rate_variable;
    }

    public function setBaseRateVariable(?float $base_rate_variable): self
    {
        $this->base_rate_variable = $base_rate_variable;

        return $this;
    }

    public function getBaseRateFix(): ?string
    {
        return $this->base_rate_fix;
    }

    public function setBaseRateFix(?string $base_rate_fix): self
    {
        $this->base_rate_fix = $base_rate_fix;

        return $this;
    }

    public function getLengthMin(): ?int
    {
        return $this->length_min;
    }

    public function setLengthMin(?int $length_min): self
    {
        $this->length_min = $length_min;

        return $this;
    }

    public function getLengthMax(): ?int
    {
        return $this->length_max;
    }

    public function setLengthMax(?int $length_max): self
    {
        $this->length_max = $length_max;

        return $this;
    }

    public function getProperty(): ?Property
    {
        return $this->property;
    }

    public function setProperty(?Property $property): self
    {
        $this->property = $property;

        return $this;
    }

    public function getPriority(): ?int
    {
        return $this->priority;
    }

    public function setPriority(int $priority): self
    {
        $this->priority = $priority;

        return $this;
    }

    public function getDefaultSelection(): ?bool
    {
        return $this->default_selection;
    }

    public function setDefaultSelection(bool $default_selection): self
    {
        $this->default_selection = $default_selection;

        return $this;
    }

    public function getDaySelection(): ?array
    {
        return $this->day_selection;
    }

    public function setDaySelection(?array $day_selection): self
    {
        $this->day_selection = $day_selection;

        return $this;
    }

    public function getPaxMin(): ?int
    {
        return $this->pax_min;
    }

    public function setPaxMin(?int $pax_min): self
    {
        $this->pax_min = $pax_min;

        return $this;
    }

    public function getPaxMax(): ?int
    {
        return $this->pax_max;
    }

    public function setPaxMax(?int $pax_max): self
    {
        $this->pax_max = $pax_max;

        return $this;
    }

    public function getOccupancyMin(): ?int
    {
        return $this->occupancy_min;
    }

    public function setOccupancyMin(?int $occupancy_min): self
    {
        $this->occupancy_min = $occupancy_min;

        return $this;
    }

    public function getOccupancyMax(): ?int
    {
        return $this->occupancy_max;
    }

    public function setOccupancyMax(?int $occupancy_max): self
    {
        $this->occupancy_max = $occupancy_max;

        return $this;
    }

    public function getAgeMin(): ?Age
    {
        return $this->age_min;
    }

    public function setAgeMin(?Age $age_min): self
    {
        $this->age_min = $age_min;

        return $this;
    }

    public function getAgeMax(): ?Age
    {
        return $this->age_max;
    }

    public function setAgeMax(?Age $age_max): self
    {
        $this->age_max = $age_max;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }
}

api/src/Form/RateRuleType.php
<?php

namespace App\Form;

use App\Entity\Age;
use App\Entity\RateRule;
use App\Entity\RateType;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Security;

class RateRuleType extends AbstractType
{
    /**
     * @var Security
     */
    private $security;

    /**
     * @var SessionInterface
     */
    private $session;

    public function __construct(
        SessionInterface $session,
        Security $security
    ) {
        $this->security = $security;
        $this->session = $session;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $user = $this->security->getUser();
        $propertyId = $this->session->get('property_id');
        $builder
            ->add('defaultSelection', HiddenType::class, [
                'data' => 0
            ])
            ->add('active')
            ->add('rate_type', EntityType::class, [
                'class' => RateType::class,
                'label' => 'Rate code *',
                'choice_label' => 'label',
                'query_builder' => function (EntityRepository $er) use ($propertyId) {
                    return $er->createQueryBuilder('rt')
                        ->where('rt.property = :property')
                        ->setParameter('property', $propertyId)
                        ->andWhere('rt.activated = 1')
                        ->orderBy('rt.label', 'ASC');
                },
                'placeholder' => 'Choose a rate type'
            ])
            ->add('date_start', DateType::class, [
                'widget' => 'single_text',
                'label' => 'Date from *',
                'required' => true,
            ])
            ->add('date_end', DateType::class, [
                'widget' => 'single_text',
                'label' => 'Date until *',
                'required' => true,
            ])
            ->add('day_selection', ChoiceType::class, [
                'choices'  => [
                    'Monday' => 'Monday',
                    'Tuesday' => 'Tuesday',
                    'Wednesday' => 'Wednesday',
                    'Thursday' => 'Thursday',
                    'Friday' => 'Friday',
                    'Saturday' => 'Saturday',
                    'Sunday' => 'Sunday',
                ],
                'multiple' => true,
                'required' => false
            ])
            ->add('base_rate_variable', NumberType::class, [
                'html5' => true,
                'label' => 'Percentage of the rate code applicable',
                'required' => false
            ])
            ->add('base_rate_fix', NumberType::class, [
                'html5' => true,
                'label' => 'Fix amount added or discounted to the rate code',
                'required' => false
            ])
            ->add('length_min', NumberType::class, [
                'html5' => true,
                'label' => 'Minimum length of stay',
                'required' => false
            ])
            ->add('length_max', NumberType::class, [
                'html5' => true,
                'label' => 'Maximum length of stay',
                'required' => false
            ])
            ->add('occupancyMin', NumberType::class, [
                'label' => 'Minimum occupancy to apply the rule',
                'html5' => true,
                'required' => false
            ])
            ->add('occupancyMax', NumberType::class, [
                'label' => 'Maximum occupancy to apply the rule',
                'html5' => true,
                'required' => false
            ])
            ->add('ageMin', EntityType::class, [
                'class' => Age::class,
                'query_builder' => function (EntityRepository $er) use ($user) {
                    return $er->createQueryBuilder('a')
                        ->where('a.brand = :brand')
                        ->setParameter('brand', $user->getBrand()->getId())
                        ->orderBy('a.label', 'ASC');
                },
                'choice_label' => 'label',
                'label' => 'Minimum age range to apply the rule',
                'required' => false,
                'choice_attr' => function ($choices, $key, $value) {
                    return ['data-min' => $choices->getMin()];
                },
            ])
            ->add('ageMax', EntityType::class, [
                'class' => Age::class,
                'query_builder' => function (EntityRepository $er) use ($user) {
                    return $er->createQueryBuilder('a')
                        ->where('a.brand = :brand')
                        ->setParameter('brand', $user->getBrand()->getId())
                        ->orderBy('a.label', 'ASC');
                },
                'choice_label' => 'label',
                'label' => 'Maximum age range to apply the rule',
                'required' => false,
                'choice_attr' => function ($choices, $key, $value) {
                    return ['data-min' => $choices->getMin()];
                },
            ])
            ->add('pax_min', NumberType::class, [
                'html5' => true,
                'label' => 'Minimum number of persons',
                'required' => false
            ])
            ->add('pax_max', NumberType::class, [
                'html5' => true,
                'label' => 'Maximum number of persons',
                'required' => false
            ])
            ->add('priority', ChoiceType::class, [
                'choices'  => [
                    'high' => 1,
                    'medium' => 2,
                    'low' => 3,
                ],
                'label' => 'Priority *'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => RateRule::class,
        ]);
    }
}

api/src/Controller/RateRuleController.php
<?php

namespace App\Controller;

use App\Entity\RateRule;
use App\Form\DefaultRateRuleType;
use App\Form\RateRuleType;
use App\Repository\RateRuleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/rate_rule")
 */
class RateRuleController extends AbstractController
{
    /**
     * @Route("/new", name="rate_rule_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $propertyId = $this->container->get('session')->get('property_id');
        $rateRule = new RateRule();
        $formType = RateRuleType::class;
        $rateRuleReposotory = $this->getDoctrine()->getRepository('App:RateRule');
        if (!$rateRuleReposotory->findDefaultRateRuleByProperty($propertyId)) {
            $formType = DefaultRateRuleType::class;
        }
        $form = $this->createForm($formType, $rateRule);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $similarRule = $rateRuleReposotory->findSimilar($propertyId, $rateRule);
            if ($similarRule) {
                return $this->render('rate_rule/new.html.twig', [
                    'rate_rule' => $rateRule,
                    'similar_rule' => $similarRule,
                    'form' => $form->createView(),
                ]);
            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($rateRule);
            $entityManager->flush();
            $this->container->get('session')->set('active-tab', 'rate_rules');

            return $this->redirectToRoute('revenue_configuration');
        }

        return $this->render('rate_rule/new.html.twig', [
            'rate_rule' => $rateRule,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/default", name="rate_rule_default", methods={"GET","POST"})
     */
    public function default(Request $request): Response
    {
        $rateRule = new RateRule();
        $form = $this->createForm(DefaultRateRuleType::class, $rateRule);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($rateRule);
            $entityManager->flush();
            $this->container->get('session')->set('active-tab', 'rate_rules');

            return $this->redirectToRoute('revenue_configuration');
        }

        return $this->render('rate_rule/new.html.twig', [
            'rate_rule' => $rateRule,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name="rate_rule_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, RateRule $rateRule): Response
    {
        $this->denyAccessUnlessGranted('edit', $rateRule);
        $formType = RateRuleType::class;
        if ($rateRule->getDefaultSelection()) {
            $formType = DefaultRateRuleType::class;
        }
        $form = $this->createForm($formType, $rateRule);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->container->get('session')->set('active-tab', 'rate_rules');

            return $this->redirectToRoute('revenue_configuration');
        }

        return $this->render('rate_rule/edit.html.twig', [
            'rate_rule' => $rateRule,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="rate_rule_delete", methods={"DELETE"})
     */
    public function delete(Request $request, RateRule $rateRule): Response
    {
        $this->denyAccessUnlessGranted('delete', $rateRule);
        if ($this->isCsrfTokenValid('delete' . $rateRule->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($rateRule);
            $entityManager->flush();
            $this->container->get('session')->set('active-tab', 'rate_rules');
        }

        return $this->redirectToRoute('revenue_configuration');
    }
}

api/templates/rate_rule/_delete_form.html.twig
<form method="post" action="{{ path('rate_rule_delete', {'id': rate_rule.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ rate_rule.id) }}">
    <button class="btn"><i class="material-icons">delete</i></button>
</form>

api/templates/rate_rule/_form.html.twig
{{ form_start(form) }}
    {% if rate_rule.defaultSelection == 0 %}
        {{ form_label(form.active) }}
        <div class="switch">
            <label>
                No
                {{ form_widget(form.active) }}
                <span class="lever"></span>
                Yes
            </label>
        </div>
    {% endif %}
    {{ form_widget(form) }}
    <button style="margin-bottom: 5px" class="btn" id="rate-rule-btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

api/templates/rate_rule/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Rate Rule{% endblock %}

{% block body %}
    {% if rate_rule.defaultSelection == 1 %}
        <h1>Edit Default Rate Rule</h1>
    {% else %}
        <h1>Edit Rate Rule</h1>
    {% endif %}

    {{ include('rate_rule/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('revenue_configuration') }}"><button style="margin-bottom: 5px" class="btn">Back to revenue configuration</button></a>

    {% if rate_rule.defaultSelection == 0 %}
        {{ include('rate_rule/_delete_form.html.twig') }}
    {% endif %}

{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script>
        $('#rate-rule-btn').click(function(){
            if (!AgeMaxBiggerAgeMin($('#rate_rule_ageMin option:selected').attr('data-min'), $('#rate_rule_ageMax option:selected').attr('data-min'))){
                return false
            }
            if (!dateFromBeforeDateUntil($('#rate_rule_date_start').val(), $('#rate_rule_date_end').val())){
                return false
            }
            if (!maxLengthBiggerMinLength($('#rate_rule_length_min').val(), $('#rate_rule_length_max').val())){
                return false
            }
            if (!maxPaxBiggerMinPax($('#rate_rule_pax_min').val(), $('#rate_rule_pax_max').val())){
                return false
            }
            if (!maxOccBiggerMinOcc($('#rate_rule_occupancyMin').val(), $('#rate_rule_occupancyMax').val())){
                return false
            }
            if (!dateInThePast($('#rate_rule_date_start').val())){
                return false
            }
        })

    </script>
{% endblock %}

api/templates/rate_rule/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Rate Rule{% endblock %}

{% block body %}
    <h1>Create a new Rate Rule</h1>

    {% if similar_rule is defined %}
        <div class="card-panel red lighten-2">There is already a rate with the same priority for these dates:
        {{ similar_rule.dateStart|date('d-m-Y') }} - {{ similar_rule.dateEnd|date('d-m-Y') }}</div>
    {% endif %}

    {{ include('rate_rule/_form.html.twig') }}
    <a href="{{ path('revenue_configuration') }}"><button class="btn">Back to revenue configuration</button></a>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script>
        $('#rate-rule-btn').click(function(){
            if (!AgeMaxBiggerAgeMin($('#rate_rule_ageMin option:selected').attr('data-min'), $('#rate_rule_ageMax option:selected').attr('data-min'))){
                return false
            }
            if (!dateFromBeforeDateUntil($('#rate_rule_date_start').val(), $('#rate_rule_date_end').val())){
                return false
            }
            if (!maxLengthBiggerMinLength($('#rate_rule_length_min').val(), $('#rate_rule_length_max').val())){
                return false
            }
            if (!maxPaxBiggerMinPax($('#rate_rule_pax_min').val(), $('#rate_rule_pax_max').val())){
                return false
            }
            if (!maxOccBiggerMinOcc($('#rate_rule_occupancyMin').val(), $('#rate_rule_occupancyMax').val())){
                return false
            }
            if (!dateInThePast($('#rate_rule_date_start').val())){
                return false
            }
        })

    </script>
{% endblock %}