api/src/Entity/Status.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\StatusRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=StatusRepository::class)
 */
class Status
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $label;

    /**
     * @ORM\ManyToOne(targetEntity=Brand::class, inversedBy="statuses")
     * @ORM\JoinColumn(nullable=false)
     */
    private $brand;

    /**
     * @ORM\OneToMany(targetEntity=Enquiry::class, mappedBy="status")
     */
    private $enquiries;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $provider_id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $default_selection;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $new_brand;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $cancel_type;

    /**
     * @ORM\Column(type="boolean")
     */
    private $optionalStatus;

    /**
     * @ORM\Column(type="boolean")
     */
    private $confirmedStatus;

    public function __construct()
    {
        $this->enquiries = new ArrayCollection();
        $this->optionalStatus = false;
        $this->confirmedStatus = false;
        $this->default_selection = false;
        $this->cancel_type = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getBrand(): ?Brand
    {
        return $this->brand;
    }

    public function setBrand(?Brand $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    /**
     * @return Collection|Enquiry[]
     */
    public function getEnquiries(): Collection
    {
        return $this->enquiries;
    }

    public function addEnquiry(Enquiry $enquiry): self
    {
        if (!$this->enquiries->contains($enquiry)) {
            $this->enquiries[] = $enquiry;
            $enquiry->setStatus($this);
        }

        return $this;
    }

    public function removeEnquiry(Enquiry $enquiry): self
    {
        if ($this->enquiries->removeElement($enquiry)) {
            // set the owning side to null (unless already changed)
            if ($enquiry->getStatus() === $this) {
                $enquiry->setStatus(null);
            }
        }

        return $this;
    }

    public function getProviderId(): ?string
    {
        return $this->provider_id;
    }

    public function setProviderId(?string $provider_id): self
    {
        $this->provider_id = $provider_id;

        return $this;
    }

    public function getDefaultSelection(): ?bool
    {
        return $this->default_selection;
    }

    public function setDefaultSelection(bool $default_selection): self
    {
        $this->default_selection = $default_selection;

        return $this;
    }

    public function getNewBrand(): ?bool
    {
        return $this->new_brand;
    }

    public function setNewBrand(?bool $new_brand): self
    {
        $this->new_brand = $new_brand;

        return $this;
    }

    public function getCancelType(): ?bool
    {
        return $this->cancel_type;
    }

    public function setCancelType(?bool $cancel_type): self
    {
        $this->cancel_type = $cancel_type;

        return $this;
    }

    public function getOptionalStatus(): ?bool
    {
        return $this->optionalStatus;
    }

    public function setOptionalStatus(bool $optionalStatus): self
    {
        $this->optionalStatus = $optionalStatus;

        return $this;
    }

    public function getConfirmedStatus(): ?bool
    {
        return $this->confirmedStatus;
    }

    public function setConfirmedStatus(bool $confirmedStatus): self
    {
        $this->confirmedStatus = $confirmedStatus;

        return $this;
    }
}

api/src/Form/PreferenceType.php
<?php

namespace App\Form;

use App\Entity\BreakdownPreferences;
use App\Entity\Currency;
use App\Entity\Language;
use App\Entity\Property;
use App\Entity\RateDisplay;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Security;

class PreferenceType extends AbstractType
{
    /**
     * @var SessionInterface
     */
    private $session;

    /**
     * @var EntityManagerInterface
     */
    private $entityManager;

    /**
     * @var Security
     */
    private $security;

    public function __construct(
        SessionInterface $session,
        EntityManagerInterface $entityManager,
        Security $security
    ) {
        $this->session = $session;
        $this->entityManager = $entityManager;
        $this->security = $security;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $propertyId = $this->session->get('property_id');
        $property = $this->entityManager->getRepository('App:Property')->find($propertyId);
        $brandId = null;
        if (null !== $this->security->getUser()->getBrand()) {
            $brandId = $this->security->getUser()->getBrand()->getId();
        }
        if (null !== $this->session->get('brand')) {
            $brandId = $this->session->get('brand')->getId();
        }

        $builder
            ->add('label', TextType::class, [
                'label' => 'Label *',
            ])
            ->add('apiKey', TextType::class, [
                'label' => 'token/key API',
                'required' => false,
            ])
            ->add('rate_display', EntityType::class, [
                'class' => RateDisplay::class,
                'choice_label' =>  'label',
                'label' => 'Rate Display *'
            ])
            ->add('emptyBedsCharged', ChoiceType::class, [
                'choices'  => [
                    'Yes' => true,
                    'No' => false,
                ],
                'label' => 'Empty beds charged per default *'
            ])
            ->add('currency', EntityType::class, [
                'class' => Currency::class,
                'choice_label' => 'label',
                'placeholder' => 'Choose a currency',
                'label' => 'Currency *',
            ])
            ->add('address', AddressType::class, [
                'label' => false,
            ])
            ->add('preference_email', PreferenceEmailType::class, [
                'label' => false,
            ])
            ->add('defaultLanguage', EntityType::class, [
                'class' => Language::class,
                'choices' => $property->getLanguage(),
                'choice_label' => 'label',
                'label' => 'Default Language *',
            ])
            ->add('language', EntityType::class, [
                'class' => Language::class,
                'choice_label' => 'label',
                'multiple' => true,
                'expanded' => false,
                'label' => 'Language *',
            ])
            ->add('breakdownTypes', EntityType::class, [
                'class' => BreakdownPreferences::class,
                'query_builder' => function (EntityRepository $er) use ($brandId) {
                    return $er->createQueryBuilder('b')
                        ->where('b.brand = :brand')
                        ->setParameter('brand', $brandId);
                },
                'choice_label' => 'label',
                'label' => 'Breakdown Type that can be used when generating automatic offer',
                'placeholder' => '',
                'multiple' => true,
                'expanded' => false,
                'required' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
        ]);
    }
}

api/templates/preference/tab/conditions.html.twig
<h4>Terms and Conditions</h4>
{% if condition_default is not empty %}
    <p><i class="medium material-icons">warning</i><br/>
        Careful, you did not choose a Default Terms & Condition Template for the languages below:<br/>
        {% for condition_default in condition_default %}<b>{{ condition_default.label }}<br/></b>{% endfor %}
    </p>
{% endif %}
<a href="{{ path('conditions_new') }}"><button class="btn">New</button></a>
<table class="table centered striped">
    <thead>
    <tr>
        <th>Default</th>
        <th>Label</th>
        <th>Language</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    {% for conditions in termsconditions %}
        <tr>
            <td>{% if conditions.defaultSelection == 1 %}Default{% endif %}</td>
            <td>{{ conditions.label }}</td>
            <td>
                {% if conditions.language.label is defined %}
                    {{ conditions.language.label }}
                {% endif %}
            </td>
            <td>
                <a href="{{ path('conditions_edit', {'id': conditions.id}) }}"><button class="btn">edit</button></a>
            </td>
        </tr>
    {% else %}
        <tr>
            <td colspan="12">no records found</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

api/templates/preference/tab/hotel_presentation.html.twig
<h4>Presentation and features for your property</h4>
<a href="{{ path('presentation_new') }}"><button class="btn">New</button></a>
<table class="table centered striped">
    <thead>
    <tr>
        <th>Label</th>
        <th>Language</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    {% for presentation in presentations %}
        <tr>
            <td>{{ presentation.label }}</td>
            <td>
                {% if presentation.language.label is defined %}
                    {{ presentation.language.label }}
                {% endif %}
            </td>
            <td>
                <a href="{{ path('presentation_edit', {'id': presentation.id}) }}"><button class="btn">edit</button></a>
            </td>
        </tr>
    {% else %}
        <tr>
            <td colspan="12">no records found</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

api/templates/preference/tab/mail_template.html.twig
<div class="col s6"><h4>Proposal</h4>
{% if mail_proposal_default is not empty %}
    <p><i class="medium material-icons">warning</i><br/>
        Be careful, you did not choose a default proposal mail template for the languages below:<br/>
        {% for mail_proposal_default in mail_proposal_default %}<b>{{ mail_proposal_default.label }}<br/></b>{% endfor %}
    </p>
{% endif %}
    <a href="{{ path('mail_template_new_proposal') }}"><button class="btn">New</button></a>
    <table class="table centered striped">
        <thead>
        <tr>
            <th>Default</th>
            <th>Label</th>
            <th>Language</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for mail_template in mail_templates|filter(mail_template => mail_template.type.label == 'Proposal') %}
            <tr>
                <td>{% if mail_template.defaultSelection == 1 %}Default{% endif %}</td>
                <td>{{ mail_template.label }}</td>
                <td>
                    {% if mail_template.language.label is defined %}
                        {{ mail_template.language.label }}
                    {% endif %}
                </td>
                <td>
                    <a href="{{ path('mail_template_edit_proposal', {'id': mail_template.id}) }}"><button class="btn">edit</button></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<div class="col s6"><h4>Pending to quote</h4>
    {% if mail_pending_default is not empty %}
        <p><i class="medium material-icons">warning</i><br/>
            Be careful, you did not choose a default template for the mail pending to quote for the languages below:<br/>
            {% for mail_pending_default in mail_pending_default %}<b>{{ mail_pending_default.label }}<br/></b>{% endfor %}
        </p>
    {% endif %}
    <a href="{{ path('mail_template_new_pending') }}"><button class="btn">New</button></a>
    <table class="table centered striped">
        <thead>
        <tr>
            <th>Default</th>
            <th>Label</th>
            <th>Language</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for mail_template in mail_templates|filter(mail_template => mail_template.type.label == 'Pending to quote') %}
            <tr>
                <td>{% if mail_template.defaultSelection == 1 %}Default{% endif %}</td>
                <td>{{ mail_template.label }}</td>
                <td>
                    {% if mail_template.language.label is defined %}
                        {{ mail_template.language.label }}
                    {% endif %}
                </td>
                <td>
                    <a href="{{ path('mail_template_edit_pending', {'id': mail_template.id}) }}"><button class="btn">edit</button></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

api/templates/preference/tab/property_preferences.html.twig
<h4>Update your preferences</h4>
<div class="col s8">
{{ form_start(preferenceForm) }}
<div class="col s6">
    <h5>Property Information</h5>
    {{ form_row(preferenceForm.label) }}
    {{ form_row(preferenceForm.address) }}
    {{ form_row(preferenceForm.currency) }}
    {{ form_row(preferenceForm.language) }}
    {{ form_row(preferenceForm.defaultLanguage) }}
    <button class="btn" style="margin-top: 20px; float: right">{{ button_label|default('Update') }}</button>
</div>
<div class="col s6">
    <h5>Enquiry Configuration</h5>
    {{ form_row(preferenceForm.preference_email) }}
    {{ form_row(preferenceForm.apiKey) }}
    {{ form_row(preferenceForm.rate_display) }}
    {{ form_row(preferenceForm.emptyBedsCharged) }}
    {{ form_row(preferenceForm.breakdownTypes) }}
    <button class="btn" style="margin-top: 20px; float: right">{{ button_label|default('Update') }}</button>
</div>
{{ form_end(preferenceForm) }}
</div>
<div class="col s4">
    <h5>Follow up preferences</h5>
    <a style="float: right" href="{{ path('app_follow_up_preference_new') }}"><button class="btn">New</button></a>
    <table class="table centered striped">
        <thead>
        <tr>
            <th>Number</th>
            <th>Days after enquiry creation</th>
        </tr>
        </thead>
        <tbody>
        {% for follow_up_preference in follow_up_preferences %}
            <tr>
                <td>{{ follow_up_preference.classification }}</td>
                <td>{{ follow_up_preference.days }}</td>
                <td>
                    <a href="{{ path('app_follow_up_preference_edit', {'id': follow_up_preference.id}) }}"><button class="btn">Edit</button></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no follow up planned</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

api/templates/preference/tab/template_proposal.html.twig
<h4>Proposal Template to send the offer</h4>
{% if proposal_default is not empty %}
    <p><i class="medium material-icons">warning</i><br/>
        Be careful, you did not choose a Default Proposal Template for the languages below:<br/>
        {% for proposal_default in proposal_default %}<b>{{ proposal_default.label }}<br/></b>{% endfor %}
    </p>
{% endif %}
<a href="{{ path('template_proposal_new') }}"><button class="btn">New</button></a>
<table class="table centered striped">
    <thead>
    <tr>
        <th>Default</th>
        <th>Label</th>
        <th>Language</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    {% for proposal_template in proposal_templates %}
        <tr>
            <td>{% if proposal_template.defaultSelection == 1 %}Default{% endif %}</td>
            <td>{{ proposal_template.label }}</td>
            <td>
                {% if proposal_template.language.label is defined %}
                    {{ proposal_template.language.label }}
                {% endif %}
            </td>
            <td>
                <a href="{{ path('template_proposal_edit', {'id': proposal_template.id}) }}"><button class="btn">edit</button></a>
            </td>
        </tr>
    {% else %}
        <tr>
            <td colspan="12">no records found</td>
        </tr>
    {% endfor %}
    </tbody>
</table>