api/src/Entity/Company.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\CompanyRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CompanyRepository::class)
 */
class Company
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $label;

    /**
     * @ORM\ManyToOne(targetEntity=Address::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $providerId;

    /**
     * @ORM\ManyToOne(targetEntity=Brand::class, inversedBy="companies")
     * @ORM\JoinColumn(nullable=false)
     */
    private $brand;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     */
    private $user;

    /**
     * @ORM\Column(type="boolean")
     */
    private $activated;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $defaultSelection;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $additional_info;

    public function __construct()
    {
        $this->activated = true;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getAddress(): ?Address
    {
        return $this->address;
    }

    public function setAddress(?Address $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getProviderId(): ?string
    {
        return $this->providerId;
    }

    public function setProviderId(?string $providerId): self
    {
        $this->providerId = $providerId;

        return $this;
    }

    public function getBrand(): ?Brand
    {
        return $this->brand;
    }

    public function setBrand(?Brand $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getActivated(): ?bool
    {
        return $this->activated;
    }

    public function setActivated(bool $activated): self
    {
        $this->activated = $activated;

        return $this;
    }

    public function getDefaultSelection(): ?bool
    {
        return $this->defaultSelection;
    }

    public function setDefaultSelection(?bool $defaultSelection): self
    {
        $this->defaultSelection = $defaultSelection;

        return $this;
    }

    public function getAdditionalInfo(): ?string
    {
        return $this->additional_info;
    }

    public function setAdditionalInfo(?string $additional_info): self
    {
        $this->additional_info = $additional_info;

        return $this;
    }
}

api/src/Form/CompanyType.php
<?php

namespace App\Form;

use App\Entity\Company;
use App\Entity\User;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Security;

class CompanyType extends AbstractType
{
    /**
     * @var Security
     */
    private $security;

    /**
     * @var SessionInterface
     */
    private $session;

    public function __construct(
        SessionInterface $session,
        Security $security
    ) {
        $this->session = $session;
        $this->security = $security;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $user = $this->security->getUser();
        $brandId = null;
        if (null !== $user->getBrand()) {
            $brandId = $user->getBrand()->getId();
        }
        if (null !== $this->session->get('brand')) {
            $brandId = $this->session->get('brand')->getId();
        }
        $builder
            ->add('label', TextType::class, [
                'label' => 'Company Name *',
            ])
            ->add('User', EntityType::class, [
                'class' => User::class,
                'query_builder' => function (EntityRepository $er) use ($user, $brandId) {
                    return $er->createQueryBuilder('p')
                        ->where('p.brand = :brand')
                        ->setParameter('brand', $brandId)
                        ->orderBy('p.firstname', 'ASC');
                },
                'choice_label' => function ($category) {
                    return $category->getFirstName() . ' ' . $category->getLastName();
                },
                'placeholder' => '',
                'label' => 'Person in charge of the account',
                'required' => false,
            ])
            ->add('address', AddressType::class, [
                'label' => false,
                'required' => false,
            ])
            ->add('additional_info', TextType::class, [
                'label' => 'Additional Information',
                'required' => false,
            ])
            ->add('defaultSelection', ChoiceType::class, [
                'choices'  => [
                    'No' => false,
                    'Yes' => true,
                ],
                'label' => 'Default selection when sending enquiry to PMS',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Company::class,
        ]);
    }
}

api/src/Controller/CompanyController.php
<?php

namespace App\Controller;

use App\Builder\CompanyUpdateBuilder;
use App\Entity\Company;
use App\Form\CompanyNewType;
use App\Form\CompanyType;
use App\Repository\CompanyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

/**
 * @Route("/company")
 */
class CompanyController extends AbstractController
{
    /**
     * @var Security
     */
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    /**
     * @Route("/brand", name="company_index", methods={"GET"})
     */
    public function index(CompanyRepository $companyRepository): Response
    {
        if ($this->isGranted('ROLE_ADMIN_WILLOW')) {
            $brand = $this->container->get('session')->get('brand');
        } else {
            $brand = $this->security->getUser()->getBrand();
        }
        $brandId = $brand->getId();

        return $this->render('company/index.html.twig', [
            'companies' => $companyRepository->findByBrand($brandId),
            'brand' => $brand,
        ]);
    }

    /**
     * @Route("/enquiry/new", name="company_enquiry_new", methods={"GET","POST"})
     */
    public function newViaEnquiry(Request $request, CompanyUpdateBuilder $builder): Response
    {
        $propertyId = $this->container->get('session')->get('property_id');
        $property = $this->getDoctrine()->getRepository('App:Property')->find($propertyId);
        $brand = $property->getBrand();
        $newCompany = new Company();
        $newCompanyForm = $this->createForm(CompanyNewType::class, $newCompany);
        $newCompanyForm->handleRequest($request);
        if ($newCompanyForm->isSubmitted() && $newCompanyForm->isValid()) {
            if ($newCompanyForm->get('save')->isClicked()) {
                $newCompany->setBrand($brand);
                $builder->addCompany($newCompany, $brand);
                $this->getDoctrine()->getManager()->persist($newCompany);
                $this->getDoctrine()->getManager()->flush();
            }
        }
        return $this->redirect($request->headers->get('referer'));
    }

    /**
     * @Route("/enquiry/{id}/edit", name="company_enquiry_edit", methods={"GET","POST"})
     */
    public function editViaEnquiry(Request $request, Company $company, CompanyUpdateBuilder $builder): Response
    {
        $form = $this->createForm(CompanyNewType::class, $company);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($form->get('save')->isClicked()) {
                $brand = $company->getBrand();
                $builder->editCompany($company, $brand);
                $this->getDoctrine()->getManager()->flush();
            }
        }
        return $this->redirect($request->headers->get('referer'));
    }

    /**
     * @Route("/brand/new", name="company_brand_new", methods={"GET","POST"})
     */
    public function newViaBrand(Request $request, CompanyUpdateBuilder $builder): Response
    {
        $company = new Company();
        $form = $this->createForm(CompanyType::class, $company);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $user = $this->security->getUser();
            $brandId = $user->getBrand()->getId();
            $brand = $entityManager->getRepository('App:Brand')->find($brandId);
            $company->setBrand($brand);
            $builder->addCompany($company, $brand);
            $entityManager->persist($company);
            $entityManager->flush();

            return $this->redirectToRoute('company_index');
        }

        return $this->render('company/new.html.twig', [
            'company' => $company,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/brand/{id}/edit", name="company_brand_edit", methods={"GET","POST"})
     */
    public function editViaBrand(Request $request, Company $company, CompanyUpdateBuilder $builder): Response
    {
        $form = $this->createForm(CompanyType::class, $company);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $brand = $company->getBrand();
            $builder->editCompany($company, $brand);
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('company_index');
        }

        return $this->render('company/edit.html.twig', [
            'company' => $company,
            'form' => $form->createView(),
        ]);
    }
}

api/templates/company/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button style="margin-bottom: 5px" class="btn" >{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

api/templates/company/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Company{% endblock %}

{% block body %}
    <h1>Edit Company</h1>

    {{ include('company/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('company_index') }}"><button style="margin-bottom: 5px" class="btn">Back to the company list</button></a>
{% endblock %}

api/templates/company/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Companies index{% endblock %}

{% block body %}
    <h1>Companies</h1>
    {% if brand.pmsGetData.label != 'Mock' %}
    <a href="{{ path('update_companies', {'id': brand.id}) }}"><button class="btn">Synchronize all companies</button></a>
    {% endif %}
    <a href="{{ path('company_brand_new') }}"><button class="btn">New</button></a>
    <h3>Active</h3>
    <table class="table">
        <thead>
            <tr>
                <th>Label</th>
                <th>Sales Manager in Charge</th>
                <th>Additional Information</th>
                <th>Default</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for company in companies|filter(company => company.activated == true) %}
            <tr>
                <td>{{ company.label }}</td>
                <td>
                {% if company.user.firstname is defined %}
                    {{ company.user.firstname }} {{ company.user.lastname }}
                {% endif %}
                </td>
                <td>{{ company.additionalInfo }}</td>
                <td>
                    {% if company.defaultSelection == true %}
                        Yes
                    {% endif %}
                </td>
                <td>
                    <a href="{{ path('company_brand_edit', {'id': company.id}) }}"><button class="btn">edit</button></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <h4>Old companies that cannot be used anymore</h4>
    <table class="table">
        <thead>
        <tr>
            <th>Label</th>
            <th>Sales Manager in Charge</th>
        </tr>
        </thead>
        <tbody>
        {% for company in companies|filter(company => company.activated == false) %}
            <tr>
                <td>{{ company.label }}</td>
                <td>
                    {% if company.user.firstname is defined %}
                        {{ company.user.firstname }} {{ company.user.lastname }}
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

api/templates/company/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add a company{% endblock %}

{% block body %}
    <h1>Create a new company</h1>

    {{ include('company/_form.html.twig') }}

    <a href="{{ path('company_index') }}"><button class="btn">Back to the company list</button></a>
{% endblock %}